# Travis integration file.
# Seattle supports Python 2.5 through 2.7, per
#   seattle.poly.edu/wiki/ProgrammersPage
#
# Travis provides OS X and Linux (specifically Ubuntu) OS instances.
# The result of this configuration will be six separate builds on
# Travis-CI VMs, 3 python versions each on Linux and OS X.


matrix:
  include:
    # Linux Instances follow, one for each dash.
    - language: python          # Language to initiate linux VM
      python: '2.7'             # Version of python to use
      os: linux                 # The OS of the VM
      install:                  # tool installation
        - sudo apt-get update
        - sudo apt-get install net-tools
    - language: python
      python: '2.6'
      os: linux
      install:
        - sudo apt-get update
        - sudo apt-get install net-tools
    - language: python
      python: '2.5'
      os: linux
      install:
        - sudo apt-get update
        - sudo apt-get install net-tools


    # OS X Instances follow
    # There is no OS X + PYTHON combination available by default, so we
    # use the "language: generic" directive and we'll install python
    # ourselves through some install directives.
    # See references:
    #   github.com/travis-ci/travis-ci/issues/2312
    #   docs.travis-ci.com/user/languages/python
    #   docs.travis-ci.com/user/multi-os/#Python-example-%28unsupported-languages%29
    # OS X Python current version (currently 2.7.11)
    - language: generic
      os: osx
      install:
          brew update;
          brew install python;
    # OS X python 2.5.6
    - language: generic
      os: osx
      install:
          brew update;
          brew install pyenv;
          pyenv install 2.5.6;
          pyenv global 2.5.6;
    # OS X python 2.6.9
    - language: generic
      os: osx
      install:
          brew update;
          brew install python;
          pyenv install 2.6.9;
          pyenv global 2.6.9;

script:
  - python --version
  - cd ./scripts
  - python initialize.py
  - python build.py -t
  - cd ../RUNNABLE
  - python utf.py -a

