# Travis integration file.
# Seattle supports Python 2.5 through 2.7, per
#   seattle.poly.edu/wiki/ProgrammersPage
#
# Travis provides OS X and Linux (specifically Ubuntu) OS instances.
# The result of this configuration will be five separate builds on
# Travis-CI VMs, 3 python versions on Linux and 2 on OS X.

# Primarily because of some manual fiddling to get python 2.5 tests
# to work, we require the following directive - we need
# non-container-based infrastructure so that Travis allows us to use
# sudo.
sudo: required

matrix:
  include:
    # Linux Instances follow, one for each dash.
    - language: python          # Language to initiate linux VM
      python: '2.7'             # Version of python to use
      os: linux                 # The OS of the VM
      env: Python='2.7' PythonBin="python" # These are environment variables we'll use.
        # In particular, PythonBin will specify the location of the python binary to use.
        # The "Python" env variable there is redundant except for OS X runs below.
      install:                  # tool installation
        sudo apt-get update;

    - language: python
      python: '2.6'
      os: linux
      env: Python='2.6' PythonBin="python"
      install:
        sudo apt-get update;

    # Because Travis-CI no longer offers the 2.5 environment by default,
    # we'll manually install 2.5.... It's not even available on the common
    # ubuntu repos, so we'll use the well-known deadsnakes repo.
    - language: python
      os: linux
      env: Python='2.5' PythonBin="/usr/bin/python2.5"
      install:
        sudo add-apt-repository "ppa:fkrull/deadsnakes" -y;
        sudo apt-get update;
        sudo apt-get install python2.5;

    # OS X Instances follow
    # There is no OS X + PYTHON combination available by default, so we
    # use the "language: generic" directive and we'll install python
    # ourselves through some install directives.
    # See references:
    #   github.com/travis-ci/travis-ci/issues/2312
    #   docs.travis-ci.com/user/languages/python
    #   docs.travis-ci.com/user/multi-os/#Python-example-%28unsupported-languages%29
    # OS X Python current version (currently 2.7.11)
    - language: generic
      os: osx
      env: Python='2.7' PythonBin="python"
      install:
          #brew update;
          brew install python;

    # OS X python 2.6.9
    # We have to use pyenv to compile and install Python 2.6.9
    # ourselves for OS X, as Travis-CI offers no OS X Python
    # environments, and homebrew no longer offers a python26
    # recipe.
    - language: generic
      os: osx
      env: Python='2.6.9' PythonBin="/Users/travis/.pyenv/versions/2.6.9/bin/python"
      install:
        #brew update;
        #brew install python26; # This is no longer available.
        pyenv install 2.6.9;
        pyenv global 2.6.9;

# These are the commands we'll run for each build, posting the python
# version we're *really* running, initializing to obtain needed common
# seattle projects, building the current seattle project, and running
# the seattle unit testing framework, with all tests.
script:
  - $PythonBin --version;
  - cd ./scripts;
  - $PythonBin initialize.py;
  - $PythonBin build.py -t;
  - cd ../RUNNABLE;
  - $PythonBin utf.py -a;

