# <~> Travis integration file.
# Seattle supports Python 2.5 through 2.7, per https://seattle.poly.edu/wiki/ProgrammersPage
# Travis provides OS X and Linux (think generally Debian-based) OS instances.
# AppVeyor provides Windows

matrix:
  include:
    - language: python          # Language to initiate linux VM
      python: '2.7'             # Type of python to use     
      os: linux                 # The OS of the VM
      install:                  # tool installation 
        - sudo apt-get update
        - sudo apt-get install net-tools
    - language: python
      python: '2.6'
      os: linux
      install:
        - sudo apt-get update
        - sudo apt-get install net-tools
    - language: python
      python: '2.5'
      os: linux
      install:
        - sudo apt-get update
        - sudo apt-get install net-tools


    # OS X Instances follow
    # Here, we are using objective-c as currently there is no MAC + PYTHON combination available by default
    # We instead use objective-c to install the python version we want
    # OS X Python current version (currently 2.7.11)
    - language: objective-c
      os: osx
      install:
          brew update;
          brew install python;
    # OS X python 2.5.6
    - language: objective-c
      os: osx
      install:
          brew update;
          brew install pyenv;
          pyenv install 2.5.6;
          pyenv global 2.5.6;
    # OS X python 2.6.9
    - language: objective-c
      os: osx
      install:
          brew update;
          brew install python;
          pyenv install 2.5.6;
          pyenv global 2.5.6;

script:
  - python --version
  - cd ./scripts
  - python initialize.py
  - python build.py -t
  - cd ../RUNNABLE
  - python utf.py -a

